services:
  eureka-discovery-service:
    build: ./eureka-discovery
    container_name: eureka-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  doctor-service:
    build: ./Doctor-service
    container_name: doctor-service
    ports:
      - '8070:8070'
    expose:
      - '8070'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL= http://eureka-discovery-service:8761/eureka
    depends_on:
      eureka-discovery-service:
        condition: service_healthy

  patient-service:
    build: ./Patient-service
    container_name: patient-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL= http://eureka-discovery-service:8761/eureka
    depends_on:
      eureka-discovery-service:
        condition: service_healthy

  gateway-service:
    build: ./Gateway-service
    container_name: gateway-service
    ports:
      - '8089:8089'
    expose:
      - '8089'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8089/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL= http://eureka-discovery-service:8761/eureka
    depends_on:
      eureka-discovery-service:
        condition: service_healthy


  rendez-vous-service:
    build: ./Rendez-vous-service
    container_name: rendez-vous-service
    ports:
      - '8090:8090'
    expose:
      - '8090'
    depends_on:
      doctor-service:
        condition: service_healthy

networks:
  app-network:
    external: true
